# Basics about Numpy library for the Python

In [37]:
#imports libraries needed
import numpy as np

# Accessing Help

In [38]:
#call help
# np.array? or
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

# Basics

In [39]:
#create array ID:[1,2,3]
l = [1,2,3]
ID = np.array(l)
print("ID: ", ID)
print("ID's shape: ", ID.shape)

ID:  [1 2 3]
ID's shape:  (3,)


In [40]:
#creating 2D array
l = [[1,2],[3,4]]
ID = np.array(l)
print("ID: ", ID)
print("ID's shape: ", ID.shape)

ID:  [[1 2]
 [3 4]]
ID's shape:  (2, 2)


In [41]:
type(ID)

numpy.ndarray

In [42]:
#=== Array with zero's ==
Z = np.zeros((4,)) 
print("Z: ", Z)
print("Z's shape:", Z.shape)

Z:  [0. 0. 0. 0.]
Z's shape: (4,)


In [43]:
Z = np.zeros((2,2)) 
print("Z: ", Z)
print("Z's shape:", Z.shape)

Z:  [[0. 0.]
 [0. 0.]]
Z's shape: (2, 2)


In [44]:
# === Array with ones's ==
O = np.ones((4,))
print("O:", O)
O[1] = 0.
print("O:", O)

O: [1. 1. 1. 1.]
O: [1. 0. 1. 1.]


In [45]:
#== linspace - returns values from an interval ==
x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num=5)
print("x: ", x)
print("x's shape:", x.shape)

x:  [ 5.   7.5 10.  12.5 15. ]
x's shape: (5,)


In [46]:
#== Eye method ==
n = 4
x = np.eye(n)
print("x: ", x) 
print("x's shape: ", x.shape) 

x:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
x's shape:  (4, 4)


In [47]:
#=== Random method ==
x = np.random.random(size=(2,3))
print("x:\n", x) 
print("x's shape: ", x.shape) 

x:
 [[0.50786915 0.80493683 0.43265539]
 [0.72246131 0.70117866 0.67908824]]
x's shape:  (2, 3)


In [48]:
print(np.pi)

3.141592653589793


# Array Indexing Numpy

In [49]:
#index starts from 0 to n-1
x = np.linspace(start=10, stop=100, num=10)
print("x:\n", x) 
print("x's shape: ", x.shape) 

x:
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
x's shape:  (10,)


In [50]:
#acessing each element
print("first element:", x[0])
print("second element:", x[1])
print("last element:", x[9])
print("last element - different way:", x[-1])

first element: 10.0
second element: 20.0
last element: 100.0
last element - different way: 100.0


In [51]:
#slicing: subarrays
print("2 first elements: ", x[0:2])
print("2 first elements - different way: ", x[:2])
print("2 last elements: ", x[-2:])

2 first elements:  [10. 20.]
2 first elements - different way:  [10. 20.]
2 last elements:  [ 90. 100.]


In [52]:
#slicing: 2D with reshape
x = x.reshape(2,5) #2 rows and 5 columns
print("x:\n",x)
print("x's shape: ", x.shape) 

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
x's shape:  (2, 5)


In [53]:
#acessing each element
print("first row, second column:", x[0,1])
print("second row, penultimate column:", x[1,-2])
print("fisrt row, last column:", x[0,4])
print("last row - last column:", x[-1,-1])

first row, second column: 20.0
second row, penultimate column: 90.0
fisrt row, last column: 50.0
last row - last column: 100.0


In [54]:
#slicing: 2D subarrays
print("x:\n", x) 
print("first row: ", x[0, :])
print("first row, from 2nd to 4th column: ", x[0, 1:4])
print("last colum", x[:, [-1]])

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
first row:  [10. 20. 30. 40. 50.]
first row, from 2nd to 4th column:  [20. 30. 40.]
last colum [[ 50.]
 [100.]]


In [55]:
#== copying using index ==
X = np.array([[1,2], [3,4]])
Y = X[0, :]
Y[1] = 10
print("X\n: ", X)
print("Y: ", Y)

X
:  [[ 1 10]
 [ 3  4]]
Y:  [ 1 10]


In [56]:
#Caution: subarrays shared memory space
X = np.array([1,2,3])
print("X before\n: ", X)
Y = X[:2]
Y[0] = -100
print("X after\n: ", X)

X before
:  [1 2 3]
X after
:  [-100    2    3]


In [57]:
#Using copy(): subarrays shared memory space
X = np.array([1,2,3])
print("X before\n: ", X)
Y = X[:2].copy()
Y[0] = -100
print("X after\n: ", X)

X before
:  [1 2 3]
X after
:  [1 2 3]


In [58]:
#An example of advanced indexing.
#Access all x` elements bigger than pi.===
X = np.array([[1,3], [11,10]])
print(X[X> np.pi])

[11 10]


# NumPy - Arithmetic Operations

In [59]:
a = np.arange(9, dtype = np.int_).reshape(3,3) 
b = np.array([10,10,10]) 
print('First array:\n',a)
print('Second array:\n',b)

First array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Second array:
 [10 10 10]


In [60]:
#Adding
print("Add 2 arrays: \n", a + b)
print("Add 2 arrays with add(): \n", np.add(a,b))
print("Add 2 to an array: \n", a + 2) #broadcasting

Add 2 arrays: 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Add 2 arrays with add(): 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Add 2 to an array: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [61]:
#Subtracting
print("Subtract 2 arrays: \n", a - b)
print("Subtract 2 arrays with subtract(): \n", np.subtract(a,b))
print("Subtract 2 from an array: \n", a - 2) #broadcasting

Subtract 2 arrays: 
 [[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]
Subtract 2 arrays with subtract(): 
 [[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]
Subtract 2 from an array: 
 [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [62]:
#Multiply
print("Multiply 2 arrays: \n", a * b)
print("Multiply 2 arrays with multiply(): \n", np.multiply(a,b))
print("Multiply 2 from an array: \n", a * 2) #broadcasting

Multiply 2 arrays: 
 [[ 0 10 20]
 [30 40 50]
 [60 70 80]]
Multiply 2 arrays with multiply(): 
 [[ 0 10 20]
 [30 40 50]
 [60 70 80]]
Multiply 2 from an array: 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [63]:
#Divide
print("Divide 2 arrays: \n", a / b)
print("Divide 2 arrays with divide(): \n", np.divide(a,b))
print("Divide 2 from an array: \n", a / 2) #broadcasting

Divide 2 arrays: 
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
Divide 2 arrays with divide(): 
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
Divide 2 from an array: 
 [[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


In [64]:
#power
a = np.array([10,100,1000]) 

print('A:\n',a) 
print ('A power 2:\n', np.power(a,2))
b = np.array([1,2,3]) 

print('Applying power function again with 2 arrays:\n',np.power(a,b))

A:
 [  10  100 1000]
A power 2:
 [    100   10000 1000000]
Applying power function again with 2 arrays:
 [        10      10000 1000000000]


In [65]:
#mod and remainder both functions returns the remainder of division

a = np.array([12,28,30]) 
b = np.array([3,5,7]) 

print("A: \n", a)
print("B: \n", b)
print('Applying mod() function:\n', np.mod(a,b)) 
print('Applying remainder() function:\n', np.remainder(a,b) )

A: 
 [12 28 30]
B: 
 [3 5 7]
Applying mod() function:
 [0 3 2]
Applying remainder() function:
 [0 3 2]


In [66]:
# when broadcasting doenst work
# np.array([1,2,3]) + np.array([1,2])

In [67]:
#Add + Subtract + Division all together
print("Combination: \n", (a+b)/(b-1))

Combination: 
 [7.5        8.25       6.16666667]


# Matrix Operations in Numpy 

In [68]:
a = np.ones((2,2)) 
b = 2 * np.eye((2))
print("a: \n", a)
print("b: \n", b)

a: 
 [[1. 1.]
 [1. 1.]]
b: 
 [[2. 0.]
 [0. 2.]]


In [69]:
#Multiply - Review
print("Multiply 2 arrays: \n", a * b)
print("Multiply 2 arrays with multiply(): \n", np.multiply(a,b))
print("Multiply 2 from an array: \n", a * 2) #broadcasting

Multiply 2 arrays: 
 [[2. 0.]
 [0. 2.]]
Multiply 2 arrays with multiply(): 
 [[2. 0.]
 [0. 2.]]
Multiply 2 from an array: 
 [[2. 2.]
 [2. 2.]]


In [70]:
# np.inner() or np.dot() same result
print("Multiply Matrices: (np.dot) \n", np.dot(a,b))
print("Multiply Matrices: (@) \n", (a@b))
print("Multiply Matrices: (.dot) \n", (a.dot(b)))
print("Multiply Matrices: (np.inner) \n", (np.inner(a,b)))

Multiply Matrices: (np.dot) 
 [[2. 2.]
 [2. 2.]]
Multiply Matrices: (@) 
 [[2. 2.]
 [2. 2.]]
Multiply Matrices: (.dot) 
 [[2. 2.]
 [2. 2.]]
Multiply Matrices: (np.inner) 
 [[2. 2.]
 [2. 2.]]


In [71]:
print("a", type(a))
print("b", type(b))

a <class 'numpy.ndarray'>
b <class 'numpy.ndarray'>


### Problem: 
Ax = c 
Where:
- x = [a,b]
- A = [[1,2], [3, -2]]
- c = [7, -11]
### Solution: 
x = inv(A) @ c

In [72]:
A = np.array([[1,2], [3, -2]])
c = np.array([7, -11])
print("A: \n", A)
print("c: \n", c)

A: 
 [[ 1  2]
 [ 3 -2]]
c: 
 [  7 -11]


In [73]:
#x = np.dot(np.linalg.inv(A), c)
x = np.linalg.inv(A) @ c
print("(a,b): \n", x.ravel())

(a,b): 
 [-1.  4.]


# Comparison 

In [74]:
# create arrays:
x = np.array([[1,2], [3,4]])
y = np.array([[1.5,3.5]])
print("x: \n",x)
print("y: \n",y)

x: 
 [[1 2]
 [3 4]]
y: 
 [[1.5 3.5]]


In [75]:
# compare with a scalar
print("Compare an array with a number (>): \n", x > 2)
print("Compare an array with a number (>=): \n", x >= 2)
print("Compare an array with a number (<): \n", x <= 2)
print("Compare an array with a number (<=): \n", x <= 2)

Compare an array with a number (>): 
 [[False False]
 [ True  True]]
Compare an array with a number (>=): 
 [[False  True]
 [ True  True]]
Compare an array with a number (<): 
 [[ True  True]
 [False False]]
Compare an array with a number (<=): 
 [[ True  True]
 [False False]]


In [76]:
# compare array and array
print("Compare arrays (>): \n", x > y)
print("Compare arrays (>=): \n", x >= y)
print("Compare arrays (<): \n", x <= y)
print("Compare arrays (<=): \n", x <= y)
print("Compare arrays (==): \n", x == y)
print("Compare arrays (==): \n", x == x)

Compare arrays (>): 
 [[False False]
 [ True  True]]
Compare arrays (>=): 
 [[False False]
 [ True  True]]
Compare arrays (<): 
 [[ True  True]
 [False False]]
Compare arrays (<=): 
 [[ True  True]
 [False False]]
Compare arrays (==): 
 [[False False]
 [False False]]
Compare arrays (==): 
 [[ True  True]
 [ True  True]]


In [77]:
#method all() compare each position of the array
equal_arrays = (x == y).all()
print(equal_arrays)

a = np.array([[1, 1], [2, 2]])
b = np.array([[1, 1], [2, 2]])
equal_arrays = (a == b).all()
print(equal_arrays)

False
True


In [78]:
print("Compare arrays (>): \n", np.greater(x, y))
print("Compare arrays (>=): \n",np.greater_equal(x, y))
print("Compare arrays (<): \n", np.less(x, y))
print("Compare arrays (<=): \n",np.less_equal(x, y))
print("Compare arrays (==): \n",np.equal(x, y))
print("Compare arrays (==): \n",np.equal(x, x))

Compare arrays (>): 
 [[False False]
 [ True  True]]
Compare arrays (>=): 
 [[False False]
 [ True  True]]
Compare arrays (<): 
 [[ True  True]
 [False False]]
Compare arrays (<=): 
 [[ True  True]
 [False False]]
Compare arrays (==): 
 [[False False]
 [False False]]
Compare arrays (==): 
 [[ True  True]
 [ True  True]]


# Boolean Indexing

In [79]:
x = np.array([[1,3,7],
            [4,11,21],
            [42,8,9]])
print("x: \n", x)

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [80]:
# return elements greater than k
k = 10
cond = x > k
print("condition: \n", cond)
print(f"elements greater than {k}:", x[cond])
print(f"quantity of elements greater than {k}:", len(x[cond]))

condition: 
 [[False False False]
 [False  True  True]
 [ True False False]]
elements greater than 10: [11 21 42]
quantity of elements greater than 10: 3


In [81]:
# even numbers
cond = x % 2 == 0
print("condition: \n", cond)
print("even numbers: \n", x[cond])

condition: 
 [[False False False]
 [ True False False]
 [ True  True False]]
even numbers: 
 [ 4 42  8]


In [82]:
# odd numbers
cond = x % 2 == 1
print("condition: \n", cond)
print("even numbers: \n", x[cond])

condition: 
 [[ True  True  True]
 [False  True  True]
 [False False  True]]
even numbers: 
 [ 1  3  7 11 21  9]


# Another operations

In [83]:
# Reshape
print("x: \n", x)
print("Change a array one column: \n", x.reshape(9,1))
print("Change a array one line: \n", x.reshape(1,9))

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
Change a array one column: 
 [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]
Change a array one line: 
 [[ 1  3  7  4 11 21 42  8  9]]


In [84]:
#Transpose
print(x.T)
print(np.transpose(x))

[[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]
[[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


In [85]:
#Sum axis = {0: column, 1 : row}
print("x: \n", x)
print("sum(x) row: \n", np.sum(x, axis=0))
print("sum(x): column \n", np.sum(x, axis=1))
print("sum(x): \n", np.sum(x)) # each number

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
sum(x) row: 
 [47 22 37]
sum(x): column 
 [11 36 59]
sum(x): 
 106


In [86]:
#mean axis = {0: column, 1 : row}
print("x: \n", x)
print("mean(x) row: \n", np.mean(x, axis=0))
print("mean(x): column \n", np.mean(x, axis=1))
print("mean(x): \n", np.mean(x)) # each number

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
mean(x) row: 
 [15.66666667  7.33333333 12.33333333]
mean(x): column 
 [ 3.66666667 12.         19.66666667]
mean(x): 
 11.777777777777779


In [87]:
#np.where, identify the indexes where a certain condition is True
# even numbers
cond = x % 2 == 0
print("condition: \n", cond)
i , j = np.where(cond)
print("rows indexes: \n", i)
print("rows indexes: \n", j)

condition: 
 [[False False False]
 [ True False False]
 [ True  True False]]
rows indexes: 
 [1 2 2]
rows indexes: 
 [0 0 1]


In [88]:
i_row = np.where(np.sum(cond, axis=1))[0]
print("Indexes fo rows where contains even numbers: ", i_row)
print("Rows with even numbers: \n", x[i_row, :])

Indexes fo rows where contains even numbers:  [1 2]
Rows with even numbers: 
 [[ 4 11 21]
 [42  8  9]]
